name: build-pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Clean project
      run: dotnet clean

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c debug --no-restore

    - name: Run integration tests
      run: dotnet test ./test/Grom.IntegrationTests/Grom.IntegrationTests.csproj --no-restore --no-build

  publish:
    if: ${{ contains(fromJson('["/release/"]'), github.ref_name) }}
    needs: build
    runs-on: ubuntu-latest
    
    env:
      NUGET_SOURCE: https://api.nuget.org/v3/index.json
      NUGET_KEY: ${{ secrets.NUGET_KEY }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Get release version from branch name
      run: |
        echo github.ref_name
        echo "PACKAGE_VERSION=$(echo ${${github.ref_name}##*/} | tr / -)" >> $GITHUB_ENV 
        echo $PACKAGE_VERSION

    # - name: Clean project
    #   run: dotnet clean

    # - name: Build
    #   run: dotnet build -c release
    
    # - name: Pack
    #   run: dotnet pack -c release -p:PackageVersion=0.1.0-alpha -o ./ ./src/Grom/Grom.csproj

    # - name: Publish
    #   run: dotnet nuget push Grom.0.1.0-alpha.nupkg --api-key $NUGET_KEY --source $NUGET_SOURCE


