name: build-pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build -c debug --no-restore

    - name: Run integration tests
      run: dotnet test ./test/Grom.IntegrationTests/Grom.IntegrationTests.csproj --no-restore --no-build

  publish:
    if: ${{ false }} #${{ contains(fromJson('["main"]'), github.ref_name) }}
    needs: build
    runs-on: ubuntu-latest
    
    env:
      NUGET_SOURCE: https://api.nuget.org/v3/index.json
      NUGET_KEY: ${{ secrets.NUGET_KEY }}
      PACKAGE_VERSION: 

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Build
      run: dotnet build -c release
    
    - name: Pack
      run: dotnet pack -c release -p:PackageVersion=0.1.0-alpha -o ./ ./src/Grom/Grom.csproj

    - name: Publish
      run: dotnet nuget push Grom.0.1.0-alpha.nupkg --api-key $FEED_APIKEY --source $NUGET_SOURCE


